# Generated by Django 2.2.3 on 2019-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('prime_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.IntegerField()),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
                ('meta_score', models.IntegerField()),
            ],
        ),
    ]
