# Generated by Django 2.2.3 on 2019-07-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190705_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='meta_score',
            field=models.IntegerField(),
        ),
    ]
